# testapp namespace
apiVersion: v1
kind: Namespace
metadata:
  name: testapp
---
# pod definition for fastapi-testapp
apiVersion: v1
kind: Pod
metadata:
  name: fastapi-testapp
  namespace: testapp
spec:
  containers:
    - name: fastapi-testapp
      image: europe-west3-docker.pkg.dev/nz-mgmt-shared-artifacts-8c85/docker-hub/sandrom/fastapi-testapp:0.0.19
      imagePullPolicy: Always
      env:
        - name: OTEL_SERVICE_NAME
          value: fastapi-testapp
        - name: OTEL_LOG_LEVEL
          value: DEBUG
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector.otel-collector:4317
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3
              key: AWS_SECRET_ACCESS_KEY
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
      ports:
        - containerPort: 8000
          name: http
          protocol: TCP
  restartPolicy: Always